// Auto-generated by scripts/build-manifest.js. Do not edit by hand.
// Bundles every levels/level-*.json so index.html can load all levels
// with one <script> tag (necessary for file:// where fetch is blocked).
(function () {
  if (!window.MAHJONG_LEVELS) window.MAHJONG_LEVELS = {};
  window.MAHJONG_LEVELS["level-1"] = {
  "levelId": "level-1",
  "slotsAmount": 6,
  "movesCount": 150,
  "difficulty": "easy",
  "stock": [
    "Panorama",
    "Salsa",
    "Virtuoso",
    "Polka",
    "Nova",
    "Bride",
    "Comet",
    "Closeup",
    "Southern",
    "Chimera",
    "Image",
    "Blue gem ring",
    "Arctic",
    "Silk",
    "Water",
    "Bouquet",
    "Celtic",
    "Asteroid",
    "Winter hat",
    "Atlantic",
    "Groom",
    "Cancan",
    "Polaroid",
    "Cluster"
  ],
  "categories": [
    {
      "categoryId": "Dances",
      "icon": false,
      "wordsIds": [
        "Samba",
        "Rumba",
        "Tango",
        "Waltz",
        "Salsa",
        "Foxtrot",
        "Polka",
        "Cancan"
      ]
    },
    {
      "categoryId": "Astro",
      "icon": false,
      "wordsIds": [
        "Star",
        "Comet",
        "Meteor",
        "Asteroid",
        "Nova",
        "Pulsar",
        "Planet",
        "Cluster"
      ]
    },
    {
      "categoryId": "Wedding",
      "icon": false,
      "wordsIds": [
        "Ceremony",
        "Proposal",
        "Bride",
        "Groom",
        "Vows",
        "Rings",
        "Bouquet",
        "Veil"
      ]
    },
    {
      "categoryId": "Photos",
      "icon": false,
      "wordsIds": [
        "Selfie",
        "Portrait",
        "Snapshot",
        "Polaroid",
        "Image",
        "Closeup",
        "Headshot",
        "Panorama"
      ]
    },
    {
      "categoryId": "Oceans",
      "icon": false,
      "wordsIds": [
        "Pacific",
        "Atlantic",
        "Indian",
        "Arctic",
        "Southern",
        "Celtic",
        "Bering",
        "Adriatic"
      ]
    },
    {
      "categoryId": "Fabrics",
      "icon": false,
      "wordsIds": [
        "Flannel",
        "Cotton",
        "Silk",
        "Satin",
        "Velvet",
        "Linen"
      ]
    },
    {
      "categoryId": "Elements",
      "icon": false,
      "wordsIds": [
        "Earth",
        "Water",
        "Fire",
        "Air"
      ]
    },
    {
      "categoryId": "Expert",
      "icon": false,
      "wordsIds": [
        "Master",
        "Maestro",
        "Guru",
        "Virtuoso",
        "Genius"
      ]
    },
    {
      "categoryId": "Mythos",
      "icon": false,
      "wordsIds": [
        "Gorgon",
        "Cyclops",
        "Chimera",
        "Basilisk"
      ]
    },
    {
      "categoryId": "Hats",
      "icon": true,
      "wordsIds": [
        "Pink wide hat",
        "Red star cap",
        "Fedora hat",
        "Winter hat",
        "Captain hat"
      ]
    },
    {
      "categoryId": "Jewelry",
      "icon": true,
      "wordsIds": [
        "Heart pendant",
        "Pearl bracelet",
        "Blue gem ring",
        "Blue earrings",
        "Blue gem pendant"
      ]
    }
  ],
  "grid": {
    "cols": 80,
    "rows": 80,
    "cellStep": 1
  },
  "stages": [
    {
      "stageId": "stage-1",
      "z": 0,
      "tiles": [
        {
          "x": 31,
          "y": 16,
          "categoryId": "Jewelry",
          "wordId": "Blue gem pendant"
        },
        {
          "x": 35,
          "y": 16,
          "categoryId": "Elements",
          "wordId": "Earth"
        },
        {
          "x": 39,
          "y": 28,
          "categoryId": "Photos",
          "wordId": "Portrait"
        },
        {
          "x": 31,
          "y": 28,
          "categoryId": "Photos",
          "wordId": "Snapshot"
        },
        {
          "x": 35,
          "y": 28,
          "categoryId": "Photos",
          "wordId": "Selfie"
        },
        {
          "x": 39,
          "y": 22,
          "categoryId": "Photos",
          "wordId": "Headshot"
        },
        {
          "x": 31,
          "y": 22,
          "categoryId": "Elements",
          "wordId": "Fire"
        },
        {
          "x": 39,
          "y": 16,
          "categoryId": "Photos",
          "wordId": "Photos"
        }
      ]
    },
    {
      "stageId": "stage-2",
      "z": 1,
      "tiles": [
        {
          "x": 29,
          "y": 13,
          "categoryId": "Expert",
          "wordId": "Guru"
        },
        {
          "x": 41,
          "y": 13,
          "categoryId": "Oceans",
          "wordId": "Bering"
        },
        {
          "x": 33,
          "y": 13,
          "categoryId": "Oceans",
          "wordId": "Adriatic"
        },
        {
          "x": 41,
          "y": 25,
          "categoryId": "Oceans",
          "wordId": "Pacific"
        },
        {
          "x": 41,
          "y": 19,
          "categoryId": "Oceans",
          "wordId": "Indian"
        },
        {
          "x": 37,
          "y": 13,
          "categoryId": "Expert",
          "wordId": "Maestro"
        },
        {
          "x": 41,
          "y": 31,
          "categoryId": "Elements",
          "wordId": "Air"
        },
        {
          "x": 37,
          "y": 31,
          "categoryId": "Jewelry",
          "wordId": "Heart pendant"
        },
        {
          "x": 29,
          "y": 19,
          "categoryId": "Jewelry",
          "wordId": "Jewelry"
        },
        {
          "x": 33,
          "y": 31,
          "categoryId": "Elements",
          "wordId": "Elements"
        },
        {
          "x": 29,
          "y": 31,
          "categoryId": "Jewelry",
          "wordId": "Blue earrings"
        },
        {
          "x": 29,
          "y": 25,
          "categoryId": "Jewelry",
          "wordId": "Pearl bracelet"
        }
      ]
    },
    {
      "stageId": "stage-3",
      "z": 2,
      "tiles": [
        {
          "x": 27,
          "y": 10,
          "categoryId": "Fabrics",
          "wordId": "Linen"
        },
        {
          "x": 43,
          "y": 10,
          "categoryId": "Fabrics",
          "wordId": "Satin"
        },
        {
          "x": 27,
          "y": 16,
          "categoryId": "Astro",
          "wordId": "Astro"
        },
        {
          "x": 35,
          "y": 10,
          "categoryId": "Fabrics",
          "wordId": "Cotton"
        },
        {
          "x": 31,
          "y": 10,
          "categoryId": "Dances",
          "wordId": "Rumba"
        },
        {
          "x": 39,
          "y": 10,
          "categoryId": "Dances",
          "wordId": "Foxtrot"
        },
        {
          "x": 27,
          "y": 22,
          "categoryId": "Astro",
          "wordId": "Pulsar"
        },
        {
          "x": 39,
          "y": 34,
          "categoryId": "Expert",
          "wordId": "Master"
        },
        {
          "x": 31,
          "y": 34,
          "categoryId": "Expert",
          "wordId": "Genius"
        },
        {
          "x": 27,
          "y": 34,
          "categoryId": "Astro",
          "wordId": "Meteor"
        },
        {
          "x": 27,
          "y": 28,
          "categoryId": "Astro",
          "wordId": "Planet"
        },
        {
          "x": 35,
          "y": 34,
          "categoryId": "Astro",
          "wordId": "Star"
        },
        {
          "x": 43,
          "y": 16,
          "categoryId": "Fabrics",
          "wordId": "Velvet"
        },
        {
          "x": 43,
          "y": 22,
          "categoryId": "Fabrics",
          "wordId": "Flannel"
        },
        {
          "x": 43,
          "y": 34,
          "categoryId": "Oceans",
          "wordId": "Oceans"
        },
        {
          "x": 43,
          "y": 28,
          "categoryId": "Expert",
          "wordId": "Expert"
        }
      ]
    },
    {
      "stageId": "stage-4",
      "z": 3,
      "tiles": [
        {
          "x": 29,
          "y": 7,
          "categoryId": "Wedding",
          "wordId": "Wedding"
        },
        {
          "x": 25,
          "y": 7,
          "categoryId": "Mythos",
          "wordId": "Mythos"
        },
        {
          "x": 33,
          "y": 7,
          "categoryId": "Mythos",
          "wordId": "Cyclops"
        },
        {
          "x": 25,
          "y": 13,
          "categoryId": "Mythos",
          "wordId": "Gorgon"
        },
        {
          "x": 45,
          "y": 7,
          "categoryId": "Wedding",
          "wordId": "Ceremony"
        },
        {
          "x": 37,
          "y": 7,
          "categoryId": "Wedding",
          "wordId": "Rings"
        },
        {
          "x": 25,
          "y": 25,
          "categoryId": "Hats",
          "wordId": "Captain hat"
        },
        {
          "x": 25,
          "y": 19,
          "categoryId": "Hats",
          "wordId": "Hats"
        },
        {
          "x": 41,
          "y": 7,
          "categoryId": "Mythos",
          "wordId": "Basilisk"
        },
        {
          "x": 45,
          "y": 37,
          "categoryId": "Dances",
          "wordId": "Waltz"
        },
        {
          "x": 41,
          "y": 37,
          "categoryId": "Fabrics",
          "wordId": "Fabrics"
        },
        {
          "x": 37,
          "y": 37,
          "categoryId": "Dances",
          "wordId": "Samba"
        },
        {
          "x": 29,
          "y": 37,
          "categoryId": "Dances",
          "wordId": "Tango"
        },
        {
          "x": 25,
          "y": 37,
          "categoryId": "Hats",
          "wordId": "Fedora hat"
        },
        {
          "x": 33,
          "y": 37,
          "categoryId": "Hats",
          "wordId": "Pink wide hat"
        },
        {
          "x": 25,
          "y": 31,
          "categoryId": "Hats",
          "wordId": "Red star cap"
        },
        {
          "x": 45,
          "y": 13,
          "categoryId": "Wedding",
          "wordId": "Proposal"
        },
        {
          "x": 45,
          "y": 19,
          "categoryId": "Wedding",
          "wordId": "Vows"
        },
        {
          "x": 45,
          "y": 25,
          "categoryId": "Wedding",
          "wordId": "Veil"
        },
        {
          "x": 45,
          "y": 31,
          "categoryId": "Dances",
          "wordId": "Dances"
        }
      ]
    }
  ]
};
  window.MAHJONG_LEVELS["level-2"] = {
  "levelId": "level-2",
  "slotsAmount": 6,
  "movesCount": 150,
  "difficulty": "normal",
  "stock": [
    "Vows",
    "Heart pendant",
    "Cluster",
    "Mythos",
    "Comet",
    "Air",
    "Bering",
    "Arctic",
    "Rumba",
    "Ceremony",
    "Pulsar",
    "Headshot",
    "Dances",
    "Southern",
    "Silk",
    "Winter hat",
    "Maestro",
    "Polka",
    "Selfie",
    "Gorgon",
    "Bouquet",
    "Closeup",
    "Indian",
    "Nova"
  ],
  "categories": [
    {
      "categoryId": "Dances",
      "icon": false,
      "wordsIds": [
        "Samba",
        "Rumba",
        "Tango",
        "Waltz",
        "Salsa",
        "Foxtrot",
        "Polka",
        "Cancan"
      ]
    },
    {
      "categoryId": "Astro",
      "icon": false,
      "wordsIds": [
        "Star",
        "Comet",
        "Meteor",
        "Asteroid",
        "Nova",
        "Pulsar",
        "Planet",
        "Cluster"
      ]
    },
    {
      "categoryId": "Wedding",
      "icon": false,
      "wordsIds": [
        "Ceremony",
        "Proposal",
        "Bride",
        "Groom",
        "Vows",
        "Rings",
        "Bouquet",
        "Veil"
      ]
    },
    {
      "categoryId": "Photos",
      "icon": false,
      "wordsIds": [
        "Selfie",
        "Portrait",
        "Snapshot",
        "Polaroid",
        "Image",
        "Closeup",
        "Headshot",
        "Panorama"
      ]
    },
    {
      "categoryId": "Oceans",
      "icon": false,
      "wordsIds": [
        "Pacific",
        "Atlantic",
        "Indian",
        "Arctic",
        "Southern",
        "Celtic",
        "Bering",
        "Adriatic"
      ]
    },
    {
      "categoryId": "Fabrics",
      "icon": false,
      "wordsIds": [
        "Flannel",
        "Cotton",
        "Silk",
        "Satin",
        "Velvet",
        "Linen"
      ]
    },
    {
      "categoryId": "Elements",
      "icon": false,
      "wordsIds": [
        "Earth",
        "Water",
        "Fire",
        "Air"
      ]
    },
    {
      "categoryId": "Expert",
      "icon": false,
      "wordsIds": [
        "Master",
        "Maestro",
        "Guru",
        "Virtuoso",
        "Genius"
      ]
    },
    {
      "categoryId": "Mythos",
      "icon": false,
      "wordsIds": [
        "Gorgon",
        "Cyclops",
        "Chimera",
        "Basilisk"
      ]
    },
    {
      "categoryId": "Hats",
      "icon": true,
      "wordsIds": [
        "Pink wide hat",
        "Red star cap",
        "Fedora hat",
        "Winter hat",
        "Captain hat"
      ]
    },
    {
      "categoryId": "Jewelry",
      "icon": true,
      "wordsIds": [
        "Heart pendant",
        "Pearl bracelet",
        "Blue gem ring",
        "Blue earrings",
        "Blue gem pendant"
      ]
    }
  ],
  "grid": {
    "cols": 80,
    "rows": 80,
    "cellStep": 1
  },
  "stages": [
    {
      "stageId": "stage-1",
      "z": 0,
      "tiles": [
        {
          "x": 31,
          "y": 16,
          "categoryId": "Oceans",
          "wordId": "Adriatic"
        },
        {
          "x": 35,
          "y": 16,
          "categoryId": "Astro",
          "wordId": "Meteor"
        },
        {
          "x": 39,
          "y": 28,
          "categoryId": "Astro",
          "wordId": "Planet"
        },
        {
          "x": 31,
          "y": 28,
          "categoryId": "Astro",
          "wordId": "Star"
        },
        {
          "x": 35,
          "y": 28,
          "categoryId": "Oceans",
          "wordId": "Celtic"
        },
        {
          "x": 39,
          "y": 22,
          "categoryId": "Oceans",
          "wordId": "Atlantic"
        },
        {
          "x": 31,
          "y": 22,
          "categoryId": "Astro",
          "wordId": "Asteroid"
        },
        {
          "x": 39,
          "y": 16,
          "categoryId": "Oceans",
          "wordId": "Pacific"
        }
      ]
    },
    {
      "stageId": "stage-2",
      "z": 1,
      "tiles": [
        {
          "x": 29,
          "y": 13,
          "categoryId": "Elements",
          "wordId": "Earth"
        },
        {
          "x": 41,
          "y": 13,
          "categoryId": "Hats",
          "wordId": "Pink wide hat"
        },
        {
          "x": 33,
          "y": 13,
          "categoryId": "Fabrics",
          "wordId": "Satin"
        },
        {
          "x": 41,
          "y": 25,
          "categoryId": "Hats",
          "wordId": "Captain hat"
        },
        {
          "x": 41,
          "y": 19,
          "categoryId": "Fabrics",
          "wordId": "Flannel"
        },
        {
          "x": 37,
          "y": 13,
          "categoryId": "Wedding",
          "wordId": "Bride"
        },
        {
          "x": 41,
          "y": 31,
          "categoryId": "Wedding",
          "wordId": "Rings"
        },
        {
          "x": 37,
          "y": 31,
          "categoryId": "Astro",
          "wordId": "Astro"
        },
        {
          "x": 29,
          "y": 19,
          "categoryId": "Elements",
          "wordId": "Water"
        },
        {
          "x": 33,
          "y": 31,
          "categoryId": "Oceans",
          "wordId": "Oceans"
        },
        {
          "x": 29,
          "y": 31,
          "categoryId": "Elements",
          "wordId": "Fire"
        },
        {
          "x": 29,
          "y": 25,
          "categoryId": "Wedding",
          "wordId": "Proposal"
        }
      ]
    },
    {
      "stageId": "stage-3",
      "z": 2,
      "tiles": [
        {
          "x": 27,
          "y": 10,
          "categoryId": "Expert",
          "wordId": "Genius"
        },
        {
          "x": 43,
          "y": 10,
          "categoryId": "Expert",
          "wordId": "Virtuoso"
        },
        {
          "x": 27,
          "y": 16,
          "categoryId": "Fabrics",
          "wordId": "Linen"
        },
        {
          "x": 35,
          "y": 10,
          "categoryId": "Dances",
          "wordId": "Tango"
        },
        {
          "x": 31,
          "y": 10,
          "categoryId": "Fabrics",
          "wordId": "Fabrics"
        },
        {
          "x": 39,
          "y": 10,
          "categoryId": "Photos",
          "wordId": "Portrait"
        },
        {
          "x": 27,
          "y": 22,
          "categoryId": "Hats",
          "wordId": "Hats"
        },
        {
          "x": 39,
          "y": 34,
          "categoryId": "Wedding",
          "wordId": "Veil"
        },
        {
          "x": 31,
          "y": 34,
          "categoryId": "Elements",
          "wordId": "Elements"
        },
        {
          "x": 27,
          "y": 34,
          "categoryId": "Hats",
          "wordId": "Red star cap"
        },
        {
          "x": 27,
          "y": 28,
          "categoryId": "Fabrics",
          "wordId": "Cotton"
        },
        {
          "x": 35,
          "y": 34,
          "categoryId": "Fabrics",
          "wordId": "Velvet"
        },
        {
          "x": 43,
          "y": 16,
          "categoryId": "Wedding",
          "wordId": "Wedding"
        },
        {
          "x": 43,
          "y": 22,
          "categoryId": "Expert",
          "wordId": "Master"
        },
        {
          "x": 43,
          "y": 34,
          "categoryId": "Hats",
          "wordId": "Fedora hat"
        },
        {
          "x": 43,
          "y": 28,
          "categoryId": "Wedding",
          "wordId": "Groom"
        }
      ]
    },
    {
      "stageId": "stage-4",
      "z": 3,
      "tiles": [
        {
          "x": 29,
          "y": 7,
          "categoryId": "Mythos",
          "wordId": "Cyclops"
        },
        {
          "x": 25,
          "y": 7,
          "categoryId": "Dances",
          "wordId": "Salsa"
        },
        {
          "x": 33,
          "y": 7,
          "categoryId": "Photos",
          "wordId": "Photos"
        },
        {
          "x": 25,
          "y": 13,
          "categoryId": "Photos",
          "wordId": "Snapshot"
        },
        {
          "x": 45,
          "y": 7,
          "categoryId": "Mythos",
          "wordId": "Basilisk"
        },
        {
          "x": 37,
          "y": 7,
          "categoryId": "Jewelry",
          "wordId": "Jewelry"
        },
        {
          "x": 25,
          "y": 25,
          "categoryId": "Photos",
          "wordId": "Polaroid"
        },
        {
          "x": 25,
          "y": 19,
          "categoryId": "Dances",
          "wordId": "Samba"
        },
        {
          "x": 41,
          "y": 7,
          "categoryId": "Dances",
          "wordId": "Foxtrot"
        },
        {
          "x": 45,
          "y": 37,
          "categoryId": "Jewelry",
          "wordId": "Blue earrings"
        },
        {
          "x": 41,
          "y": 37,
          "categoryId": "Photos",
          "wordId": "Panorama"
        },
        {
          "x": 37,
          "y": 37,
          "categoryId": "Dances",
          "wordId": "Cancan"
        },
        {
          "x": 29,
          "y": 37,
          "categoryId": "Jewelry",
          "wordId": "Blue gem pendant"
        },
        {
          "x": 25,
          "y": 37,
          "categoryId": "Photos",
          "wordId": "Image"
        },
        {
          "x": 33,
          "y": 37,
          "categoryId": "Expert",
          "wordId": "Guru"
        },
        {
          "x": 25,
          "y": 31,
          "categoryId": "Expert",
          "wordId": "Expert"
        },
        {
          "x": 45,
          "y": 13,
          "categoryId": "Jewelry",
          "wordId": "Blue gem ring"
        },
        {
          "x": 45,
          "y": 19,
          "categoryId": "Mythos",
          "wordId": "Chimera"
        },
        {
          "x": 45,
          "y": 25,
          "categoryId": "Jewelry",
          "wordId": "Pearl bracelet"
        },
        {
          "x": 45,
          "y": 31,
          "categoryId": "Dances",
          "wordId": "Waltz"
        }
      ]
    }
  ]
};
  window.MAHJONG_LEVELS["level-3"] = {
  "levelId": "level-3",
  "slotsAmount": 6,
  "movesCount": 150,
  "difficulty": "hard",
  "stock": [
    "Pulsar",
    "Pearl bracelet",
    "Dances",
    "Rings",
    "Indian",
    "Tango",
    "Bride",
    "Red star cap",
    "Ceremony",
    "Jewelry",
    "Panorama",
    "Satin",
    "Adriatic",
    "Fabrics",
    "Hats",
    "Portrait",
    "Gorgon",
    "Asteroid",
    "Nova",
    "Bering",
    "Genius",
    "Earth",
    "Selfie",
    "Samba"
  ],
  "categories": [
    {
      "categoryId": "Dances",
      "icon": false,
      "wordsIds": [
        "Samba",
        "Rumba",
        "Tango",
        "Waltz",
        "Salsa",
        "Foxtrot",
        "Polka",
        "Cancan"
      ]
    },
    {
      "categoryId": "Astro",
      "icon": false,
      "wordsIds": [
        "Star",
        "Comet",
        "Meteor",
        "Asteroid",
        "Nova",
        "Pulsar",
        "Planet",
        "Cluster"
      ]
    },
    {
      "categoryId": "Wedding",
      "icon": false,
      "wordsIds": [
        "Ceremony",
        "Proposal",
        "Bride",
        "Groom",
        "Vows",
        "Rings",
        "Bouquet",
        "Veil"
      ]
    },
    {
      "categoryId": "Photos",
      "icon": false,
      "wordsIds": [
        "Selfie",
        "Portrait",
        "Snapshot",
        "Polaroid",
        "Image",
        "Closeup",
        "Headshot",
        "Panorama"
      ]
    },
    {
      "categoryId": "Oceans",
      "icon": false,
      "wordsIds": [
        "Pacific",
        "Atlantic",
        "Indian",
        "Arctic",
        "Southern",
        "Celtic",
        "Bering",
        "Adriatic"
      ]
    },
    {
      "categoryId": "Fabrics",
      "icon": false,
      "wordsIds": [
        "Flannel",
        "Cotton",
        "Silk",
        "Satin",
        "Velvet",
        "Linen"
      ]
    },
    {
      "categoryId": "Elements",
      "icon": false,
      "wordsIds": [
        "Earth",
        "Water",
        "Fire",
        "Air"
      ]
    },
    {
      "categoryId": "Expert",
      "icon": false,
      "wordsIds": [
        "Master",
        "Maestro",
        "Guru",
        "Virtuoso",
        "Genius"
      ]
    },
    {
      "categoryId": "Mythos",
      "icon": false,
      "wordsIds": [
        "Gorgon",
        "Cyclops",
        "Chimera",
        "Basilisk"
      ]
    },
    {
      "categoryId": "Hats",
      "icon": true,
      "wordsIds": [
        "Pink wide hat",
        "Red star cap",
        "Fedora hat",
        "Winter hat",
        "Captain hat"
      ]
    },
    {
      "categoryId": "Jewelry",
      "icon": true,
      "wordsIds": [
        "Heart pendant",
        "Pearl bracelet",
        "Blue gem ring",
        "Blue earrings",
        "Blue gem pendant"
      ]
    }
  ],
  "grid": {
    "cols": 80,
    "rows": 80,
    "cellStep": 1
  },
  "stages": [
    {
      "stageId": "stage-1",
      "z": 0,
      "tiles": [
        {
          "x": 31,
          "y": 16,
          "categoryId": "Astro",
          "wordId": "Cluster"
        },
        {
          "x": 35,
          "y": 16,
          "categoryId": "Expert",
          "wordId": "Master"
        },
        {
          "x": 39,
          "y": 28,
          "categoryId": "Expert",
          "wordId": "Virtuoso"
        },
        {
          "x": 31,
          "y": 28,
          "categoryId": "Expert",
          "wordId": "Guru"
        },
        {
          "x": 35,
          "y": 28,
          "categoryId": "Astro",
          "wordId": "Meteor"
        },
        {
          "x": 39,
          "y": 22,
          "categoryId": "Astro",
          "wordId": "Planet"
        },
        {
          "x": 31,
          "y": 22,
          "categoryId": "Oceans",
          "wordId": "Celtic"
        },
        {
          "x": 39,
          "y": 16,
          "categoryId": "Photos",
          "wordId": "Headshot"
        }
      ]
    },
    {
      "stageId": "stage-2",
      "z": 1,
      "tiles": [
        {
          "x": 29,
          "y": 13,
          "categoryId": "Photos",
          "wordId": "Snapshot"
        },
        {
          "x": 41,
          "y": 13,
          "categoryId": "Astro",
          "wordId": "Comet"
        },
        {
          "x": 33,
          "y": 13,
          "categoryId": "Mythos",
          "wordId": "Basilisk"
        },
        {
          "x": 41,
          "y": 25,
          "categoryId": "Oceans",
          "wordId": "Pacific"
        },
        {
          "x": 41,
          "y": 19,
          "categoryId": "Photos",
          "wordId": "Polaroid"
        },
        {
          "x": 37,
          "y": 13,
          "categoryId": "Oceans",
          "wordId": "Arctic"
        },
        {
          "x": 41,
          "y": 31,
          "categoryId": "Oceans",
          "wordId": "Atlantic"
        },
        {
          "x": 37,
          "y": 31,
          "categoryId": "Photos",
          "wordId": "Image"
        },
        {
          "x": 29,
          "y": 19,
          "categoryId": "Expert",
          "wordId": "Expert"
        },
        {
          "x": 33,
          "y": 31,
          "categoryId": "Expert",
          "wordId": "Maestro"
        },
        {
          "x": 29,
          "y": 31,
          "categoryId": "Astro",
          "wordId": "Star"
        },
        {
          "x": 29,
          "y": 25,
          "categoryId": "Mythos",
          "wordId": "Chimera"
        }
      ]
    },
    {
      "stageId": "stage-3",
      "z": 2,
      "tiles": [
        {
          "x": 27,
          "y": 10,
          "categoryId": "Hats",
          "wordId": "Fedora hat"
        },
        {
          "x": 43,
          "y": 10,
          "categoryId": "Photos",
          "wordId": "Photos"
        },
        {
          "x": 27,
          "y": 16,
          "categoryId": "Mythos",
          "wordId": "Mythos"
        },
        {
          "x": 35,
          "y": 10,
          "categoryId": "Elements",
          "wordId": "Air"
        },
        {
          "x": 31,
          "y": 10,
          "categoryId": "Jewelry",
          "wordId": "Heart pendant"
        },
        {
          "x": 39,
          "y": 10,
          "categoryId": "Wedding",
          "wordId": "Veil"
        },
        {
          "x": 27,
          "y": 22,
          "categoryId": "Dances",
          "wordId": "Salsa"
        },
        {
          "x": 39,
          "y": 34,
          "categoryId": "Dances",
          "wordId": "Cancan"
        },
        {
          "x": 31,
          "y": 34,
          "categoryId": "Oceans",
          "wordId": "Southern"
        },
        {
          "x": 27,
          "y": 34,
          "categoryId": "Mythos",
          "wordId": "Cyclops"
        },
        {
          "x": 27,
          "y": 28,
          "categoryId": "Wedding",
          "wordId": "Groom"
        },
        {
          "x": 35,
          "y": 34,
          "categoryId": "Astro",
          "wordId": "Astro"
        },
        {
          "x": 43,
          "y": 16,
          "categoryId": "Oceans",
          "wordId": "Oceans"
        },
        {
          "x": 43,
          "y": 22,
          "categoryId": "Fabrics",
          "wordId": "Silk"
        },
        {
          "x": 43,
          "y": 34,
          "categoryId": "Wedding",
          "wordId": "Proposal"
        },
        {
          "x": 43,
          "y": 28,
          "categoryId": "Photos",
          "wordId": "Closeup"
        }
      ]
    },
    {
      "stageId": "stage-4",
      "z": 3,
      "tiles": [
        {
          "x": 29,
          "y": 7,
          "categoryId": "Fabrics",
          "wordId": "Linen"
        },
        {
          "x": 25,
          "y": 7,
          "categoryId": "Dances",
          "wordId": "Waltz"
        },
        {
          "x": 33,
          "y": 7,
          "categoryId": "Hats",
          "wordId": "Captain hat"
        },
        {
          "x": 25,
          "y": 13,
          "categoryId": "Dances",
          "wordId": "Rumba"
        },
        {
          "x": 45,
          "y": 7,
          "categoryId": "Wedding",
          "wordId": "Wedding"
        },
        {
          "x": 37,
          "y": 7,
          "categoryId": "Jewelry",
          "wordId": "Blue gem ring"
        },
        {
          "x": 25,
          "y": 25,
          "categoryId": "Elements",
          "wordId": "Water"
        },
        {
          "x": 25,
          "y": 19,
          "categoryId": "Hats",
          "wordId": "Winter hat"
        },
        {
          "x": 41,
          "y": 7,
          "categoryId": "Elements",
          "wordId": "Elements"
        },
        {
          "x": 45,
          "y": 37,
          "categoryId": "Fabrics",
          "wordId": "Velvet"
        },
        {
          "x": 41,
          "y": 37,
          "categoryId": "Dances",
          "wordId": "Polka"
        },
        {
          "x": 37,
          "y": 37,
          "categoryId": "Wedding",
          "wordId": "Bouquet"
        },
        {
          "x": 29,
          "y": 37,
          "categoryId": "Jewelry",
          "wordId": "Blue gem pendant"
        },
        {
          "x": 25,
          "y": 37,
          "categoryId": "Hats",
          "wordId": "Pink wide hat"
        },
        {
          "x": 33,
          "y": 37,
          "categoryId": "Elements",
          "wordId": "Fire"
        },
        {
          "x": 25,
          "y": 31,
          "categoryId": "Dances",
          "wordId": "Foxtrot"
        },
        {
          "x": 45,
          "y": 13,
          "categoryId": "Fabrics",
          "wordId": "Flannel"
        },
        {
          "x": 45,
          "y": 19,
          "categoryId": "Jewelry",
          "wordId": "Blue earrings"
        },
        {
          "x": 45,
          "y": 25,
          "categoryId": "Wedding",
          "wordId": "Vows"
        },
        {
          "x": 45,
          "y": 31,
          "categoryId": "Fabrics",
          "wordId": "Cotton"
        }
      ]
    }
  ]
};
  window.MAHJONG_LEVELS["level-4"] = {
  "levelId": "level-4",
  "slotsAmount": 6,
  "movesCount": 150,
  "difficulty": "veryhard",
  "stock": [
    "Maestro",
    "Jewelry",
    "Earth",
    "Bering",
    "Elements",
    "Photos",
    "Waltz",
    "Astro",
    "Ceremony",
    "Fabrics",
    "Basilisk",
    "Groom",
    "Adriatic",
    "Salsa",
    "Comet",
    "Silk",
    "Arctic",
    "Fedora hat",
    "Asteroid",
    "Dances",
    "Selfie",
    "Heart pendant",
    "Rings",
    "Hats"
  ],
  "categories": [
    {
      "categoryId": "Dances",
      "icon": false,
      "wordsIds": [
        "Samba",
        "Rumba",
        "Tango",
        "Waltz",
        "Salsa",
        "Foxtrot",
        "Polka",
        "Cancan"
      ]
    },
    {
      "categoryId": "Astro",
      "icon": false,
      "wordsIds": [
        "Star",
        "Comet",
        "Meteor",
        "Asteroid",
        "Nova",
        "Pulsar",
        "Planet",
        "Cluster"
      ]
    },
    {
      "categoryId": "Wedding",
      "icon": false,
      "wordsIds": [
        "Ceremony",
        "Proposal",
        "Bride",
        "Groom",
        "Vows",
        "Rings",
        "Bouquet",
        "Veil"
      ]
    },
    {
      "categoryId": "Photos",
      "icon": false,
      "wordsIds": [
        "Selfie",
        "Portrait",
        "Snapshot",
        "Polaroid",
        "Image",
        "Closeup",
        "Headshot",
        "Panorama"
      ]
    },
    {
      "categoryId": "Oceans",
      "icon": false,
      "wordsIds": [
        "Pacific",
        "Atlantic",
        "Indian",
        "Arctic",
        "Southern",
        "Celtic",
        "Bering",
        "Adriatic"
      ]
    },
    {
      "categoryId": "Fabrics",
      "icon": false,
      "wordsIds": [
        "Flannel",
        "Cotton",
        "Silk",
        "Satin",
        "Velvet",
        "Linen"
      ]
    },
    {
      "categoryId": "Elements",
      "icon": false,
      "wordsIds": [
        "Earth",
        "Water",
        "Fire",
        "Air"
      ]
    },
    {
      "categoryId": "Expert",
      "icon": false,
      "wordsIds": [
        "Master",
        "Maestro",
        "Guru",
        "Virtuoso",
        "Genius"
      ]
    },
    {
      "categoryId": "Mythos",
      "icon": false,
      "wordsIds": [
        "Gorgon",
        "Cyclops",
        "Chimera",
        "Basilisk"
      ]
    },
    {
      "categoryId": "Hats",
      "icon": true,
      "wordsIds": [
        "Pink wide hat",
        "Red star cap",
        "Fedora hat",
        "Winter hat",
        "Captain hat"
      ]
    },
    {
      "categoryId": "Jewelry",
      "icon": true,
      "wordsIds": [
        "Heart pendant",
        "Pearl bracelet",
        "Blue gem ring",
        "Blue earrings",
        "Blue gem pendant"
      ]
    }
  ],
  "grid": {
    "cols": 80,
    "rows": 80,
    "cellStep": 1
  },
  "stages": [
    {
      "stageId": "stage-1",
      "z": 0,
      "tiles": [
        {
          "x": 31,
          "y": 16,
          "categoryId": "Oceans",
          "wordId": "Southern"
        },
        {
          "x": 35,
          "y": 16,
          "categoryId": "Wedding",
          "wordId": "Bride"
        },
        {
          "x": 39,
          "y": 28,
          "categoryId": "Expert",
          "wordId": "Guru"
        },
        {
          "x": 31,
          "y": 28,
          "categoryId": "Wedding",
          "wordId": "Vows"
        },
        {
          "x": 35,
          "y": 28,
          "categoryId": "Expert",
          "wordId": "Virtuoso"
        },
        {
          "x": 39,
          "y": 22,
          "categoryId": "Oceans",
          "wordId": "Atlantic"
        },
        {
          "x": 31,
          "y": 22,
          "categoryId": "Expert",
          "wordId": "Genius"
        },
        {
          "x": 39,
          "y": 16,
          "categoryId": "Mythos",
          "wordId": "Gorgon"
        }
      ]
    },
    {
      "stageId": "stage-2",
      "z": 1,
      "tiles": [
        {
          "x": 29,
          "y": 13,
          "categoryId": "Astro",
          "wordId": "Meteor"
        },
        {
          "x": 41,
          "y": 13,
          "categoryId": "Mythos",
          "wordId": "Chimera"
        },
        {
          "x": 33,
          "y": 13,
          "categoryId": "Oceans",
          "wordId": "Pacific"
        },
        {
          "x": 41,
          "y": 25,
          "categoryId": "Oceans",
          "wordId": "Celtic"
        },
        {
          "x": 41,
          "y": 19,
          "categoryId": "Photos",
          "wordId": "Portrait"
        },
        {
          "x": 37,
          "y": 13,
          "categoryId": "Wedding",
          "wordId": "Veil"
        },
        {
          "x": 41,
          "y": 31,
          "categoryId": "Astro",
          "wordId": "Pulsar"
        },
        {
          "x": 37,
          "y": 31,
          "categoryId": "Expert",
          "wordId": "Master"
        },
        {
          "x": 29,
          "y": 19,
          "categoryId": "Expert",
          "wordId": "Expert"
        },
        {
          "x": 33,
          "y": 31,
          "categoryId": "Mythos",
          "wordId": "Cyclops"
        },
        {
          "x": 29,
          "y": 31,
          "categoryId": "Wedding",
          "wordId": "Bouquet"
        },
        {
          "x": 29,
          "y": 25,
          "categoryId": "Astro",
          "wordId": "Star"
        }
      ]
    },
    {
      "stageId": "stage-3",
      "z": 2,
      "tiles": [
        {
          "x": 27,
          "y": 10,
          "categoryId": "Fabrics",
          "wordId": "Satin"
        },
        {
          "x": 43,
          "y": 10,
          "categoryId": "Astro",
          "wordId": "Cluster"
        },
        {
          "x": 27,
          "y": 16,
          "categoryId": "Oceans",
          "wordId": "Oceans"
        },
        {
          "x": 35,
          "y": 10,
          "categoryId": "Dances",
          "wordId": "Foxtrot"
        },
        {
          "x": 31,
          "y": 10,
          "categoryId": "Photos",
          "wordId": "Headshot"
        },
        {
          "x": 39,
          "y": 10,
          "categoryId": "Hats",
          "wordId": "Red star cap"
        },
        {
          "x": 27,
          "y": 22,
          "categoryId": "Fabrics",
          "wordId": "Flannel"
        },
        {
          "x": 39,
          "y": 34,
          "categoryId": "Photos",
          "wordId": "Polaroid"
        },
        {
          "x": 31,
          "y": 34,
          "categoryId": "Wedding",
          "wordId": "Proposal"
        },
        {
          "x": 27,
          "y": 34,
          "categoryId": "Oceans",
          "wordId": "Indian"
        },
        {
          "x": 27,
          "y": 28,
          "categoryId": "Dances",
          "wordId": "Samba"
        },
        {
          "x": 35,
          "y": 34,
          "categoryId": "Mythos",
          "wordId": "Mythos"
        },
        {
          "x": 43,
          "y": 16,
          "categoryId": "Wedding",
          "wordId": "Wedding"
        },
        {
          "x": 43,
          "y": 22,
          "categoryId": "Photos",
          "wordId": "Panorama"
        },
        {
          "x": 43,
          "y": 34,
          "categoryId": "Dances",
          "wordId": "Tango"
        },
        {
          "x": 43,
          "y": 28,
          "categoryId": "Astro",
          "wordId": "Planet"
        }
      ]
    },
    {
      "stageId": "stage-4",
      "z": 3,
      "tiles": [
        {
          "x": 29,
          "y": 7,
          "categoryId": "Fabrics",
          "wordId": "Cotton"
        },
        {
          "x": 25,
          "y": 7,
          "categoryId": "Jewelry",
          "wordId": "Blue gem ring"
        },
        {
          "x": 33,
          "y": 7,
          "categoryId": "Photos",
          "wordId": "Closeup"
        },
        {
          "x": 25,
          "y": 13,
          "categoryId": "Jewelry",
          "wordId": "Blue gem pendant"
        },
        {
          "x": 45,
          "y": 7,
          "categoryId": "Hats",
          "wordId": "Winter hat"
        },
        {
          "x": 37,
          "y": 7,
          "categoryId": "Elements",
          "wordId": "Fire"
        },
        {
          "x": 25,
          "y": 25,
          "categoryId": "Dances",
          "wordId": "Rumba"
        },
        {
          "x": 25,
          "y": 19,
          "categoryId": "Photos",
          "wordId": "Snapshot"
        },
        {
          "x": 41,
          "y": 7,
          "categoryId": "Dances",
          "wordId": "Polka"
        },
        {
          "x": 45,
          "y": 37,
          "categoryId": "Jewelry",
          "wordId": "Pearl bracelet"
        },
        {
          "x": 41,
          "y": 37,
          "categoryId": "Astro",
          "wordId": "Nova"
        },
        {
          "x": 37,
          "y": 37,
          "categoryId": "Hats",
          "wordId": "Captain hat"
        },
        {
          "x": 29,
          "y": 37,
          "categoryId": "Elements",
          "wordId": "Air"
        },
        {
          "x": 25,
          "y": 37,
          "categoryId": "Photos",
          "wordId": "Image"
        },
        {
          "x": 33,
          "y": 37,
          "categoryId": "Dances",
          "wordId": "Cancan"
        },
        {
          "x": 25,
          "y": 31,
          "categoryId": "Jewelry",
          "wordId": "Blue earrings"
        },
        {
          "x": 45,
          "y": 13,
          "categoryId": "Fabrics",
          "wordId": "Linen"
        },
        {
          "x": 45,
          "y": 19,
          "categoryId": "Elements",
          "wordId": "Water"
        },
        {
          "x": 45,
          "y": 25,
          "categoryId": "Hats",
          "wordId": "Pink wide hat"
        },
        {
          "x": 45,
          "y": 31,
          "categoryId": "Fabrics",
          "wordId": "Velvet"
        }
      ]
    }
  ]
};
  window.MAHJONG_LEVELS["level-5"] = {
  "levelId": "level-5",
  "slotsAmount": 5,
  "movesCount": 100,
  "difficulty": "veryhard",
  "stock": [
    "Gorgon",
    "Waltz",
    "Cotton",
    "Photos",
    "Bouquet",
    "Bering",
    "Celtic",
    "Planet",
    "Ceremony",
    "Nova",
    "Portrait",
    "Asteroid",
    "Image",
    "Flannel",
    "Chimera",
    "Samba",
    "Atlantic",
    "Velvet",
    "Proposal",
    "Rumba",
    "Wedding",
    "Astro",
    "Panorama",
    "Indian",
    "Earth",
    "Arctic",
    "Elements",
    "Rings",
    "Blue earrings",
    "Foxtrot",
    "Red star cap",
    "Polka",
    "Vows",
    "Silk",
    "Hats",
    "Guru",
    "Snapshot",
    "Maestro",
    "Meteor",
    "Selfie",
    "Pink wide hat",
    "Oceans",
    "Blue gem pendant",
    "Jewelry",
    "Master",
    "Salsa"
  ],
  "categories": [
    {
      "categoryId": "Dances",
      "icon": false,
      "wordsIds": [
        "Samba",
        "Rumba",
        "Tango",
        "Waltz",
        "Salsa",
        "Foxtrot",
        "Polka",
        "Cancan"
      ]
    },
    {
      "categoryId": "Astro",
      "icon": false,
      "wordsIds": [
        "Star",
        "Comet",
        "Meteor",
        "Asteroid",
        "Nova",
        "Pulsar",
        "Planet",
        "Cluster"
      ]
    },
    {
      "categoryId": "Wedding",
      "icon": false,
      "wordsIds": [
        "Ceremony",
        "Proposal",
        "Bride",
        "Groom",
        "Vows",
        "Rings",
        "Bouquet",
        "Veil"
      ]
    },
    {
      "categoryId": "Photos",
      "icon": false,
      "wordsIds": [
        "Selfie",
        "Portrait",
        "Snapshot",
        "Polaroid",
        "Image",
        "Closeup",
        "Headshot",
        "Panorama"
      ]
    },
    {
      "categoryId": "Oceans",
      "icon": false,
      "wordsIds": [
        "Pacific",
        "Atlantic",
        "Indian",
        "Arctic",
        "Southern",
        "Celtic",
        "Bering",
        "Adriatic"
      ]
    },
    {
      "categoryId": "Fabrics",
      "icon": false,
      "wordsIds": [
        "Flannel",
        "Cotton",
        "Silk",
        "Satin",
        "Velvet",
        "Linen"
      ]
    },
    {
      "categoryId": "Elements",
      "icon": false,
      "wordsIds": [
        "Earth",
        "Water",
        "Fire",
        "Air"
      ]
    },
    {
      "categoryId": "Expert",
      "icon": false,
      "wordsIds": [
        "Master",
        "Maestro",
        "Guru",
        "Virtuoso",
        "Genius"
      ]
    },
    {
      "categoryId": "Mythos",
      "icon": false,
      "wordsIds": [
        "Gorgon",
        "Cyclops",
        "Chimera",
        "Basilisk"
      ]
    },
    {
      "categoryId": "Hats",
      "icon": true,
      "wordsIds": [
        "Pink wide hat",
        "Red star cap",
        "Fedora hat",
        "Winter hat",
        "Captain hat"
      ]
    },
    {
      "categoryId": "Jewelry",
      "icon": true,
      "wordsIds": [
        "Heart pendant",
        "Pearl bracelet",
        "Blue gem ring",
        "Blue earrings",
        "Blue gem pendant"
      ]
    }
  ],
  "grid": {
    "cols": 80,
    "rows": 60,
    "cellStep": 1
  },
  "stages": [
    {
      "stageId": "stage-1",
      "z": 0,
      "tiles": [
        {
          "x": 27,
          "y": 12,
          "categoryId": "Photos",
          "wordId": "Headshot"
        },
        {
          "x": 31,
          "y": 12,
          "categoryId": "Oceans",
          "wordId": "Southern"
        },
        {
          "x": 35,
          "y": 12,
          "categoryId": "Expert",
          "wordId": "Genius"
        },
        {
          "x": 39,
          "y": 12,
          "categoryId": "Fabrics",
          "wordId": "Linen"
        },
        {
          "x": 27,
          "y": 18,
          "categoryId": "Mythos",
          "wordId": "Mythos"
        },
        {
          "x": 27,
          "y": 24,
          "categoryId": "Fabrics",
          "wordId": "Satin"
        },
        {
          "x": 31,
          "y": 24,
          "categoryId": "Mythos",
          "wordId": "Basilisk"
        },
        {
          "x": 35,
          "y": 24,
          "categoryId": "Dances",
          "wordId": "Dances"
        },
        {
          "x": 39,
          "y": 24,
          "categoryId": "Mythos",
          "wordId": "Cyclops"
        },
        {
          "x": 39,
          "y": 18,
          "categoryId": "Expert",
          "wordId": "Virtuoso"
        },
        {
          "x": 31,
          "y": 6,
          "categoryId": "Fabrics",
          "wordId": "Fabrics"
        },
        {
          "x": 35,
          "y": 6,
          "categoryId": "Astro",
          "wordId": "Cluster"
        },
        {
          "x": 31,
          "y": 30,
          "categoryId": "Dances",
          "wordId": "Tango"
        },
        {
          "x": 35,
          "y": 30,
          "categoryId": "Dances",
          "wordId": "Cancan"
        },
        {
          "x": 31,
          "y": 18,
          "categoryId": "Photos",
          "wordId": "Closeup"
        },
        {
          "x": 35,
          "y": 18,
          "categoryId": "Oceans",
          "wordId": "Pacific"
        }
      ]
    },
    {
      "stageId": "stage-2",
      "z": 1,
      "tiles": [
        {
          "x": 29,
          "y": 9,
          "categoryId": "Jewelry",
          "wordId": "Pearl bracelet"
        },
        {
          "x": 33,
          "y": 9,
          "categoryId": "Wedding",
          "wordId": "Groom"
        },
        {
          "x": 37,
          "y": 9,
          "categoryId": "Hats",
          "wordId": "Winter hat"
        },
        {
          "x": 29,
          "y": 15,
          "categoryId": "Elements",
          "wordId": "Fire"
        },
        {
          "x": 29,
          "y": 21,
          "categoryId": "Wedding",
          "wordId": "Veil"
        },
        {
          "x": 37,
          "y": 27,
          "categoryId": "Expert",
          "wordId": "Expert"
        },
        {
          "x": 37,
          "y": 15,
          "categoryId": "Jewelry",
          "wordId": "Heart pendant"
        },
        {
          "x": 29,
          "y": 27,
          "categoryId": "Photos",
          "wordId": "Polaroid"
        },
        {
          "x": 37,
          "y": 21,
          "categoryId": "Elements",
          "wordId": "Water"
        },
        {
          "x": 33,
          "y": 27,
          "categoryId": "Oceans",
          "wordId": "Adriatic"
        },
        {
          "x": 33,
          "y": 15,
          "categoryId": "Astro",
          "wordId": "Pulsar"
        },
        {
          "x": 33,
          "y": 21,
          "categoryId": "Hats",
          "wordId": "Fedora hat"
        }
      ]
    },
    {
      "stageId": "stage-3",
      "z": 2,
      "tiles": [
        {
          "x": 31,
          "y": 12,
          "categoryId": "Astro",
          "wordId": "Star"
        },
        {
          "x": 35,
          "y": 12,
          "categoryId": "Jewelry",
          "wordId": "Blue gem ring"
        },
        {
          "x": 31,
          "y": 18,
          "categoryId": "Wedding",
          "wordId": "Bride"
        },
        {
          "x": 35,
          "y": 18,
          "categoryId": "Hats",
          "wordId": "Captain hat"
        },
        {
          "x": 31,
          "y": 24,
          "categoryId": "Elements",
          "wordId": "Air"
        },
        {
          "x": 35,
          "y": 24,
          "categoryId": "Astro",
          "wordId": "Comet"
        }
      ]
    }
  ]
};
  window.MAHJONG_LEVELS["level-6"] = {
  "levelId": "level-6",
  "slotsAmount": 5,
  "movesCount": 100,
  "difficulty": "veryhard",
  "stock": [
    "Portrait",
    "Virtuoso",
    "Southern",
    "Bouquet",
    "Bride",
    "Panorama",
    "Proposal",
    "Blue gem ring",
    "Planet",
    "Indian",
    "Cotton",
    "Earth",
    "Closeup",
    "Wedding",
    "Snapshot",
    "Headshot",
    "Master",
    "Jewelry",
    "Cyclops",
    "Pearl bracelet",
    "Maestro",
    "Pulsar",
    "Velvet",
    "Hats",
    "Arctic",
    "Meteor",
    "Image",
    "Salsa",
    "Polka",
    "Chimera",
    "Elements",
    "Fabrics",
    "Genius",
    "Waltz",
    "Atlantic",
    "Vows",
    "Linen",
    "Samba",
    "Foxtrot",
    "Gorgon",
    "Oceans",
    "Selfie",
    "Groom",
    "Rumba",
    "Comet",
    "Nova",
    "Captain hat",
    "Astro",
    "Bering",
    "Pink wide hat"
  ],
  "categories": [
    {
      "categoryId": "Dances",
      "icon": false,
      "wordsIds": [
        "Samba",
        "Rumba",
        "Tango",
        "Waltz",
        "Salsa",
        "Foxtrot",
        "Polka",
        "Cancan"
      ]
    },
    {
      "categoryId": "Astro",
      "icon": false,
      "wordsIds": [
        "Star",
        "Comet",
        "Meteor",
        "Asteroid",
        "Nova",
        "Pulsar",
        "Planet",
        "Cluster"
      ]
    },
    {
      "categoryId": "Wedding",
      "icon": false,
      "wordsIds": [
        "Ceremony",
        "Proposal",
        "Bride",
        "Groom",
        "Vows",
        "Rings",
        "Bouquet",
        "Veil"
      ]
    },
    {
      "categoryId": "Photos",
      "icon": false,
      "wordsIds": [
        "Selfie",
        "Portrait",
        "Snapshot",
        "Polaroid",
        "Image",
        "Closeup",
        "Headshot",
        "Panorama"
      ]
    },
    {
      "categoryId": "Oceans",
      "icon": false,
      "wordsIds": [
        "Pacific",
        "Atlantic",
        "Indian",
        "Arctic",
        "Southern",
        "Celtic",
        "Bering",
        "Adriatic"
      ]
    },
    {
      "categoryId": "Fabrics",
      "icon": false,
      "wordsIds": [
        "Flannel",
        "Cotton",
        "Silk",
        "Satin",
        "Velvet",
        "Linen"
      ]
    },
    {
      "categoryId": "Elements",
      "icon": false,
      "wordsIds": [
        "Earth",
        "Water",
        "Fire",
        "Air"
      ]
    },
    {
      "categoryId": "Expert",
      "icon": false,
      "wordsIds": [
        "Master",
        "Maestro",
        "Guru",
        "Virtuoso",
        "Genius"
      ]
    },
    {
      "categoryId": "Mythos",
      "icon": false,
      "wordsIds": [
        "Gorgon",
        "Cyclops",
        "Chimera",
        "Basilisk"
      ]
    },
    {
      "categoryId": "Hats",
      "icon": true,
      "wordsIds": [
        "Pink wide hat",
        "Red star cap",
        "Fedora hat",
        "Winter hat",
        "Captain hat"
      ]
    },
    {
      "categoryId": "Jewelry",
      "icon": true,
      "wordsIds": [
        "Heart pendant",
        "Pearl bracelet",
        "Blue gem ring",
        "Blue earrings",
        "Blue gem pendant"
      ]
    }
  ],
  "grid": {
    "cols": 80,
    "rows": 60,
    "cellStep": 1
  },
  "stages": [
    {
      "stageId": "stage-1",
      "z": 0,
      "tiles": [
        {
          "x": 27,
          "y": 13,
          "categoryId": "Jewelry",
          "wordId": "Blue gem pendant"
        },
        {
          "x": 31,
          "y": 13,
          "categoryId": "Dances",
          "wordId": "Dances"
        },
        {
          "x": 27,
          "y": 19,
          "categoryId": "Mythos",
          "wordId": "Mythos"
        },
        {
          "x": 27,
          "y": 25,
          "categoryId": "Jewelry",
          "wordId": "Blue earrings"
        },
        {
          "x": 31,
          "y": 19,
          "categoryId": "Photos",
          "wordId": "Photos"
        },
        {
          "x": 31,
          "y": 25,
          "categoryId": "Dances",
          "wordId": "Cancan"
        },
        {
          "x": 39,
          "y": 25,
          "categoryId": "Photos",
          "wordId": "Polaroid"
        },
        {
          "x": 39,
          "y": 37,
          "categoryId": "Expert",
          "wordId": "Guru"
        },
        {
          "x": 35,
          "y": 31,
          "categoryId": "Astro",
          "wordId": "Star"
        },
        {
          "x": 39,
          "y": 31,
          "categoryId": "Jewelry",
          "wordId": "Heart pendant"
        },
        {
          "x": 35,
          "y": 25,
          "categoryId": "Mythos",
          "wordId": "Basilisk"
        },
        {
          "x": 35,
          "y": 37,
          "categoryId": "Dances",
          "wordId": "Tango"
        },
        {
          "x": 31,
          "y": 31,
          "categoryId": "Expert",
          "wordId": "Expert"
        },
        {
          "x": 35,
          "y": 19,
          "categoryId": "Astro",
          "wordId": "Cluster"
        }
      ]
    },
    {
      "stageId": "stage-2",
      "z": 1,
      "tiles": [
        {
          "x": 29,
          "y": 16,
          "categoryId": "Fabrics",
          "wordId": "Satin"
        },
        {
          "x": 29,
          "y": 22,
          "categoryId": "Wedding",
          "wordId": "Ceremony"
        },
        {
          "x": 33,
          "y": 22,
          "categoryId": "Oceans",
          "wordId": "Pacific"
        },
        {
          "x": 29,
          "y": 28,
          "categoryId": "Fabrics",
          "wordId": "Flannel"
        },
        {
          "x": 33,
          "y": 28,
          "categoryId": "Elements",
          "wordId": "Fire"
        },
        {
          "x": 37,
          "y": 22,
          "categoryId": "Hats",
          "wordId": "Winter hat"
        },
        {
          "x": 37,
          "y": 28,
          "categoryId": "Wedding",
          "wordId": "Veil"
        },
        {
          "x": 33,
          "y": 16,
          "categoryId": "Elements",
          "wordId": "Air"
        },
        {
          "x": 33,
          "y": 34,
          "categoryId": "Oceans",
          "wordId": "Adriatic"
        },
        {
          "x": 37,
          "y": 34,
          "categoryId": "Astro",
          "wordId": "Asteroid"
        }
      ]
    },
    {
      "stageId": "stage-3",
      "z": 2,
      "tiles": [
        {
          "x": 31,
          "y": 19,
          "categoryId": "Hats",
          "wordId": "Red star cap"
        },
        {
          "x": 35,
          "y": 19,
          "categoryId": "Fabrics",
          "wordId": "Silk"
        },
        {
          "x": 31,
          "y": 25,
          "categoryId": "Elements",
          "wordId": "Water"
        },
        {
          "x": 35,
          "y": 25,
          "categoryId": "Wedding",
          "wordId": "Rings"
        },
        {
          "x": 31,
          "y": 31,
          "categoryId": "Oceans",
          "wordId": "Celtic"
        },
        {
          "x": 35,
          "y": 31,
          "categoryId": "Hats",
          "wordId": "Fedora hat"
        }
      ]
    }
  ]
};
  window.MAHJONG_LEVELS["level-7"] = {
  "levelId": "level-7",
  "slotsAmount": 5,
  "movesCount": 200,
  "difficulty": "veryhard",
  "stock": [
    "Expert",
    "Fire",
    "Snapshot",
    "Portrait",
    "Meteor",
    "Red star cap",
    "Blue gem pendant",
    "Hats",
    "Pulsar",
    "Bouquet",
    "Atlantic",
    "Cancan",
    "Photos",
    "Oceans",
    "Basilisk",
    "Tango",
    "Mythos",
    "Satin",
    "Asteroid",
    "Ceremony",
    "Southern",
    "Maestro",
    "Waltz",
    "Celtic",
    "Wedding",
    "Proposal",
    "Winter hat",
    "Salsa",
    "Flannel",
    "Arctic",
    "Veil",
    "Rings",
    "Samba",
    "Image",
    "Master",
    "Heart pendant",
    "Nova",
    "Selfie",
    "Comet",
    "Polka",
    "Star",
    "Adriatic",
    "Cluster",
    "Elements",
    "Silk",
    "Blue earrings",
    "Panorama",
    "Linen",
    "Velvet"
  ],
  "categories": [
    {
      "categoryId": "Dances",
      "icon": false,
      "wordsIds": [
        "Samba",
        "Rumba",
        "Tango",
        "Waltz",
        "Salsa",
        "Foxtrot",
        "Polka",
        "Cancan"
      ]
    },
    {
      "categoryId": "Astro",
      "icon": false,
      "wordsIds": [
        "Star",
        "Comet",
        "Meteor",
        "Asteroid",
        "Nova",
        "Pulsar",
        "Planet",
        "Cluster"
      ]
    },
    {
      "categoryId": "Wedding",
      "icon": false,
      "wordsIds": [
        "Ceremony",
        "Proposal",
        "Bride",
        "Groom",
        "Vows",
        "Rings",
        "Bouquet",
        "Veil"
      ]
    },
    {
      "categoryId": "Photos",
      "icon": false,
      "wordsIds": [
        "Selfie",
        "Portrait",
        "Snapshot",
        "Polaroid",
        "Image",
        "Closeup",
        "Headshot",
        "Panorama"
      ]
    },
    {
      "categoryId": "Oceans",
      "icon": false,
      "wordsIds": [
        "Pacific",
        "Atlantic",
        "Indian",
        "Arctic",
        "Southern",
        "Celtic",
        "Bering",
        "Adriatic"
      ]
    },
    {
      "categoryId": "Fabrics",
      "icon": false,
      "wordsIds": [
        "Flannel",
        "Cotton",
        "Silk",
        "Satin",
        "Velvet",
        "Linen"
      ]
    },
    {
      "categoryId": "Elements",
      "icon": false,
      "wordsIds": [
        "Earth",
        "Water",
        "Fire",
        "Air"
      ]
    },
    {
      "categoryId": "Expert",
      "icon": false,
      "wordsIds": [
        "Master",
        "Maestro",
        "Guru",
        "Virtuoso",
        "Genius"
      ]
    },
    {
      "categoryId": "Mythos",
      "icon": false,
      "wordsIds": [
        "Gorgon",
        "Cyclops",
        "Chimera",
        "Basilisk"
      ]
    },
    {
      "categoryId": "Hats",
      "icon": true,
      "wordsIds": [
        "Pink wide hat",
        "Red star cap",
        "Fedora hat",
        "Winter hat",
        "Captain hat"
      ]
    },
    {
      "categoryId": "Jewelry",
      "icon": true,
      "wordsIds": [
        "Heart pendant",
        "Pearl bracelet",
        "Blue gem ring",
        "Blue earrings",
        "Blue gem pendant"
      ]
    }
  ],
  "grid": {
    "cols": 80,
    "rows": 60,
    "cellStep": 1
  },
  "stages": [
    {
      "stageId": "stage-1",
      "z": 0,
      "tiles": [
        {
          "x": 29,
          "y": 12,
          "categoryId": "Hats",
          "wordId": "Captain hat"
        },
        {
          "x": 33,
          "y": 12,
          "categoryId": "Mythos",
          "wordId": "Gorgon"
        },
        {
          "x": 37,
          "y": 24,
          "categoryId": "Astro",
          "wordId": "Planet"
        },
        {
          "x": 27,
          "y": 18,
          "categoryId": "Fabrics",
          "wordId": "Cotton"
        },
        {
          "x": 37,
          "y": 12,
          "categoryId": "Jewelry",
          "wordId": "Blue gem ring"
        },
        {
          "x": 31,
          "y": 18,
          "categoryId": "Astro",
          "wordId": "Astro"
        },
        {
          "x": 25,
          "y": 24,
          "categoryId": "Mythos",
          "wordId": "Chimera"
        },
        {
          "x": 29,
          "y": 24,
          "categoryId": "Jewelry",
          "wordId": "Pearl bracelet"
        },
        {
          "x": 35,
          "y": 6,
          "categoryId": "Dances",
          "wordId": "Dances"
        },
        {
          "x": 35,
          "y": 18,
          "categoryId": "Hats",
          "wordId": "Fedora hat"
        },
        {
          "x": 27,
          "y": 6,
          "categoryId": "Mythos",
          "wordId": "Cyclops"
        },
        {
          "x": 25,
          "y": 12,
          "categoryId": "Fabrics",
          "wordId": "Fabrics"
        },
        {
          "x": 33,
          "y": 24,
          "categoryId": "Dances",
          "wordId": "Foxtrot"
        },
        {
          "x": 23,
          "y": 6,
          "categoryId": "Hats",
          "wordId": "Pink wide hat"
        },
        {
          "x": 31,
          "y": 6,
          "categoryId": "Jewelry",
          "wordId": "Jewelry"
        },
        {
          "x": 23,
          "y": 18,
          "categoryId": "Dances",
          "wordId": "Rumba"
        }
      ]
    },
    {
      "stageId": "stage-2",
      "z": 1,
      "tiles": [
        {
          "x": 27,
          "y": 9,
          "categoryId": "Expert",
          "wordId": "Genius"
        },
        {
          "x": 31,
          "y": 9,
          "categoryId": "Wedding",
          "wordId": "Bride"
        },
        {
          "x": 25,
          "y": 15,
          "categoryId": "Elements",
          "wordId": "Air"
        },
        {
          "x": 35,
          "y": 9,
          "categoryId": "Oceans",
          "wordId": "Indian"
        },
        {
          "x": 29,
          "y": 15,
          "categoryId": "Photos",
          "wordId": "Polaroid"
        },
        {
          "x": 33,
          "y": 15,
          "categoryId": "Expert",
          "wordId": "Virtuoso"
        },
        {
          "x": 27,
          "y": 21,
          "categoryId": "Wedding",
          "wordId": "Vows"
        },
        {
          "x": 31,
          "y": 21,
          "categoryId": "Oceans",
          "wordId": "Bering"
        },
        {
          "x": 35,
          "y": 21,
          "categoryId": "Elements",
          "wordId": "Water"
        }
      ]
    },
    {
      "stageId": "stage-3",
      "z": 2,
      "tiles": [
        {
          "x": 31,
          "y": 15,
          "categoryId": "Oceans",
          "wordId": "Pacific"
        },
        {
          "x": 29,
          "y": 9,
          "categoryId": "Photos",
          "wordId": "Headshot"
        },
        {
          "x": 33,
          "y": 21,
          "categoryId": "Photos",
          "wordId": "Closeup"
        },
        {
          "x": 27,
          "y": 15,
          "categoryId": "Wedding",
          "wordId": "Groom"
        },
        {
          "x": 33,
          "y": 9,
          "categoryId": "Expert",
          "wordId": "Guru"
        },
        {
          "x": 29,
          "y": 21,
          "categoryId": "Elements",
          "wordId": "Earth"
        }
      ]
    }
  ]
};
  window.MAHJONG_LEVELS["level-8"] = {
  "levelId": "level-1",
  "slotsAmount": 4,
  "movesCount": 200,
  "difficulty": "veryhard",
  "stock": [
    "Veil",
    "Pink wide hat",
    "Cotton",
    "Comet",
    "Rings",
    "Astro",
    "Blue gem ring",
    "Virtuoso",
    "Heart pendant",
    "Expert",
    "Meteor",
    "Chimera",
    "Arctic",
    "Blue gem pendant",
    "Snapshot",
    "Star",
    "Elements",
    "Mythos",
    "Celtic",
    "Hats",
    "Image",
    "Bering",
    "Silk",
    "Flannel",
    "Polaroid",
    "Waltz",
    "Atlantic",
    "Wedding",
    "Water",
    "Samba",
    "Foxtrot",
    "Blue earrings",
    "Master",
    "Vows",
    "Salsa",
    "Asteroid",
    "Satin",
    "Southern",
    "Pulsar",
    "Cancan",
    "Selfie",
    "Ceremony",
    "Closeup",
    "Red star cap",
    "Oceans",
    "Headshot",
    "Groom",
    "Tango"
  ],
  "categories": [
    {
      "categoryId": "Dances",
      "icon": false,
      "wordsIds": [
        "Samba",
        "Rumba",
        "Tango",
        "Waltz",
        "Salsa",
        "Foxtrot",
        "Polka",
        "Cancan"
      ]
    },
    {
      "categoryId": "Astro",
      "icon": false,
      "wordsIds": [
        "Star",
        "Comet",
        "Meteor",
        "Asteroid",
        "Nova",
        "Pulsar",
        "Planet",
        "Cluster"
      ]
    },
    {
      "categoryId": "Wedding",
      "icon": false,
      "wordsIds": [
        "Ceremony",
        "Proposal",
        "Bride",
        "Groom",
        "Vows",
        "Rings",
        "Bouquet",
        "Veil"
      ]
    },
    {
      "categoryId": "Photos",
      "icon": false,
      "wordsIds": [
        "Selfie",
        "Portrait",
        "Snapshot",
        "Polaroid",
        "Image",
        "Closeup",
        "Headshot",
        "Panorama"
      ]
    },
    {
      "categoryId": "Oceans",
      "icon": false,
      "wordsIds": [
        "Pacific",
        "Atlantic",
        "Indian",
        "Arctic",
        "Southern",
        "Celtic",
        "Bering",
        "Adriatic"
      ]
    },
    {
      "categoryId": "Fabrics",
      "icon": false,
      "wordsIds": [
        "Flannel",
        "Cotton",
        "Silk",
        "Satin",
        "Velvet",
        "Linen"
      ]
    },
    {
      "categoryId": "Elements",
      "icon": false,
      "wordsIds": [
        "Earth",
        "Water",
        "Fire",
        "Air"
      ]
    },
    {
      "categoryId": "Expert",
      "icon": false,
      "wordsIds": [
        "Master",
        "Maestro",
        "Guru",
        "Virtuoso",
        "Genius"
      ]
    },
    {
      "categoryId": "Mythos",
      "icon": false,
      "wordsIds": [
        "Gorgon",
        "Cyclops",
        "Chimera",
        "Basilisk"
      ]
    },
    {
      "categoryId": "Hats",
      "icon": true,
      "wordsIds": [
        "Pink wide hat",
        "Red star cap",
        "Fedora hat",
        "Winter hat",
        "Captain hat"
      ]
    },
    {
      "categoryId": "Jewelry",
      "icon": true,
      "wordsIds": [
        "Heart pendant",
        "Pearl bracelet",
        "Blue gem ring",
        "Blue earrings",
        "Blue gem pendant"
      ]
    }
  ],
  "grid": {
    "cols": 80,
    "rows": 60,
    "cellStep": 1
  },
  "stages": [
    {
      "stageId": "stage-1",
      "z": 0,
      "tiles": [
        {
          "x": 20,
          "y": 11,
          "categoryId": "Elements",
          "wordId": "Earth"
        },
        {
          "x": 20,
          "y": 29,
          "categoryId": "Fabrics",
          "wordId": "Velvet"
        },
        {
          "x": 24,
          "y": 11,
          "categoryId": "Expert",
          "wordId": "Guru"
        },
        {
          "x": 28,
          "y": 11,
          "categoryId": "Hats",
          "wordId": "Winter hat"
        },
        {
          "x": 32,
          "y": 11,
          "categoryId": "Photos",
          "wordId": "Portrait"
        },
        {
          "x": 36,
          "y": 11,
          "categoryId": "Elements",
          "wordId": "Air"
        },
        {
          "x": 36,
          "y": 29,
          "categoryId": "Dances",
          "wordId": "Polka"
        },
        {
          "x": 24,
          "y": 29,
          "categoryId": "Dances",
          "wordId": "Rumba"
        },
        {
          "x": 28,
          "y": 29,
          "categoryId": "Jewelry",
          "wordId": "Pearl bracelet"
        },
        {
          "x": 32,
          "y": 29,
          "categoryId": "Fabrics",
          "wordId": "Linen"
        },
        {
          "x": 24,
          "y": 17,
          "categoryId": "Expert",
          "wordId": "Genius"
        },
        {
          "x": 24,
          "y": 23,
          "categoryId": "Fabrics",
          "wordId": "Fabrics"
        },
        {
          "x": 28,
          "y": 17,
          "categoryId": "Hats",
          "wordId": "Fedora hat"
        },
        {
          "x": 32,
          "y": 17,
          "categoryId": "Photos",
          "wordId": "Panorama"
        },
        {
          "x": 28,
          "y": 23,
          "categoryId": "Dances",
          "wordId": "Dances"
        },
        {
          "x": 32,
          "y": 23,
          "categoryId": "Jewelry",
          "wordId": "Jewelry"
        }
      ]
    },
    {
      "stageId": "stage-2",
      "z": 1,
      "tiles": [
        {
          "x": 22,
          "y": 14,
          "categoryId": "Astro",
          "wordId": "Nova"
        },
        {
          "x": 22,
          "y": 20,
          "categoryId": "Astro",
          "wordId": "Planet"
        },
        {
          "x": 22,
          "y": 26,
          "categoryId": "Hats",
          "wordId": "Captain hat"
        },
        {
          "x": 26,
          "y": 17,
          "categoryId": "Oceans",
          "wordId": "Adriatic"
        },
        {
          "x": 26,
          "y": 23,
          "categoryId": "Elements",
          "wordId": "Fire"
        },
        {
          "x": 30,
          "y": 17,
          "categoryId": "Wedding",
          "wordId": "Bride"
        },
        {
          "x": 30,
          "y": 23,
          "categoryId": "Expert",
          "wordId": "Maestro"
        },
        {
          "x": 34,
          "y": 14,
          "categoryId": "Mythos",
          "wordId": "Basilisk"
        },
        {
          "x": 34,
          "y": 20,
          "categoryId": "Mythos",
          "wordId": "Gorgon"
        },
        {
          "x": 34,
          "y": 26,
          "categoryId": "Photos",
          "wordId": "Photos"
        }
      ]
    },
    {
      "stageId": "stage-3",
      "z": 2,
      "tiles": [
        {
          "x": 24,
          "y": 14,
          "categoryId": "Oceans",
          "wordId": "Pacific"
        },
        {
          "x": 28,
          "y": 17,
          "categoryId": "Astro",
          "wordId": "Cluster"
        },
        {
          "x": 32,
          "y": 14,
          "categoryId": "Wedding",
          "wordId": "Proposal"
        },
        {
          "x": 24,
          "y": 26,
          "categoryId": "Oceans",
          "wordId": "Indian"
        },
        {
          "x": 28,
          "y": 23,
          "categoryId": "Mythos",
          "wordId": "Cyclops"
        },
        {
          "x": 32,
          "y": 26,
          "categoryId": "Wedding",
          "wordId": "Bouquet"
        }
      ]
    }
  ]
};
  window.MAHJONG_LEVEL_KEYS = ["level-1","level-2","level-3","level-4","level-5","level-6","level-7","level-8"];
})();
